version: "3.9"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: clouddevops-portfolio:latest
    container_name: clouddevops-portfolio
    ports:
      - "8080:8080"        # Visit http://localhost:8080
    restart: unless-stopped
